version: "3"

services:
  app:
    depends_on:
      - mongodb
    build: .
    restart: always
    environment:
      - IS_CONTAINER_RUN=1
      - RUN_RATE=86400
      - CURRENCY_API_KEY=
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo_volume:/data/db


volumes:
  mongo_volume: